services:
  siuntu-savitarna:
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - appdata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: siuntudb
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
volumes:
    appdata:


