name: siuntu-savitarna-irenginys

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - appdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: siuntudb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
    networks:
      - app-network
    restart: always
    ports:
      - 3306:3306
  flutter-web:
    container_name: flutter-web
    build:
      context: C:\Users\Mykol\IdeaProjects\siuntu_web_app
      dockerfile: Dockerfile
    ports:
      - 8081:80
    networks:
      - app-network
  siuntu-savitarna:
    restart: always
    container_name: rest-api
    build:
      context: C:\Users\Mykol\IdeaProjects\SiuntuSavitarna
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
        - mysqldb
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  appdata:

networks:
  app-network:
